# Generated by Selenium IDE
import pandas as pd
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from config import user_name,password,url

driver = webdriver.Chrome()
vars = {}

# naviage to sit  
# def naviage(url):
driver.get(url)
driver.set_window_size(1280, 690)


def login(username,password):
    # driver.find_element(By.ID, "loginform_UserName").click()
    driver.find_element(By.ID, "loginform_UserName").send_keys(username)
    # driver.find_element(By.ID, "loginform_Password").click()
    driver.find_element(By.ID, "loginform_Password").send_keys(password)
    driver.find_element(By.ID, "loginform_LoginButton").click()
    
def go_to_reporter():
    driver.find_element(By.LINK_TEXT, "Reports").click()
    
    

#naviage(url)
login(user_name,password)
driver.find_element(By.LINK_TEXT, "Reports").click()

# def select_params():
#     # Date selection
driver.find_element(By.ID, "MainArea_FromMonth").click()
dropdown = driver.find_element(By.ID, "MainArea_FromMonth")
dropdown.find_element(By.XPATH, "//option[. = '01']").click()
driver.find_element(By.ID, "MainArea_FromMonth").click()

driver.find_element(By.ID, "MainArea_FromYear").click()
driver.find_element(By.ID, "MainArea_FromYear").click()

driver.find_element(By.ID, "MainArea_ToMonth").click()
dropdown = driver.find_element(By.ID, "MainArea_ToMonth")
dropdown.find_element(By.XPATH, "//option[. = '01']").click()
driver.find_element(By.ID, "MainArea_ToMonth").click()
driver.find_element(By.ID, "MainArea_ToYear").click()
driver.find_element(By.ID, "MainArea_ToYear").click()

  

dropdown = driver.find_element(By.ID, "MainArea_FrTo_Label")
dropdown.find_element(By.XPATH, "//option[. = '- All Labels -']").click()
dropdown = driver.find_element(By.ID, "MainArea_FrTo_Label")
dropdown.find_element(By.XPATH, "//option[. = '- All Naxos Labels -']").click()
driver.find_element(By.CSS_SELECTOR, "#MainArea_FrTo_DSP > option:nth-child(1)").click()


element = driver.find_element(By.ID, "MainArea_FrTo_Country")
actions = ActionChains(driver)

actions.move_to_element(element).click_and_hold().perform()

element = driver.find_element(By.ID, "MainArea_FrTo_Country")
actions.move_to_element(element).perform()

element = driver.find_element(By.ID, "MainArea_FrTo_Country")
actions.move_to_element(element).release().perform()

dropdown = driver.find_element(By.ID, "MainArea_FrTo_Country")
dropdown.find_element(By.XPATH, "//option[. = '- All Countries -']").click()
dropdown = driver.find_element(By.ID, "MainArea_FrTo_Country")
dropdown.find_element(By.XPATH, "//option[. = 'UNITED STATES OF AMERICA']").click()
dropdown = driver.find_element(By.ID, "MainArea_FrTo_DeliveryType")
dropdown.find_element(By.XPATH, "//option[. = '- All Delivery Type -']").click()
dropdown = driver.find_element(By.ID, "MainArea_FrTo_DeliveryType")
dropdown.find_element(By.XPATH, "//option[. = 'DOWNLOAD']").click()
driver.find_element(By.ID, "MainArea_FrTo_ReportingOffice").click()
dropdown = driver.find_element(By.ID, "MainArea_FrTo_ReportingOffice")
dropdown.find_element(By.XPATH, "//option[. = 'Naxos of America Inc.']").click()
driver.find_element(By.ID, "MainArea_FrTo_ReportingOffice").click()
driver.find_element(By.ID, "MainArea_FrTo_Item").click()
driver.find_element(By.ID, "MainArea_FrTo_Item").send_keys("8.579025")
driver.find_element(By.ID, "MainArea_ReportType").click()
driver.find_element(By.ID, "MainArea_ReportType").click()
driver.find_element(By.ID, "MainArea_FileFormat").click()
driver.find_element(By.ID, "MainArea_FileFormat").click()
driver.find_element(By.ID, "MainArea_CompressExport").click()
driver.find_element(By.ID, "MainArea_CompressExport").click()
driver.find_element(By.ID, "MainArea_ExportButton").click()
  

def download_report():
    driver.find_element(By.ID, "MainArea_ExportButton").click()


driver.quit()
