# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUntitled():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_untitled(self):
    self.driver.get("http://dspreporter.naxos.com/Login.aspx?ReturnUrl=%2f")
    self.driver.set_window_size(1280, 690)
    self.driver.find_element(By.ID, "loginform_UserName").click()
    self.driver.find_element(By.ID, "loginform_UserName").send_keys("mlugo")
    self.driver.find_element(By.ID, "loginform_Password").click()
    self.driver.find_element(By.ID, "loginform_Password").send_keys("zGaE5821;{")
    self.driver.find_element(By.ID, "loginform_LoginButton").click()
    self.driver.find_element(By.LINK_TEXT, "Reports").click()

    self.driver.find_element(By.ID, "MainArea_FromMonth").click()
    dropdown = self.driver.find_element(By.ID, "MainArea_FromMonth")
    dropdown.find_element(By.XPATH, "//option[. = '01']").click()
    self.driver.find_element(By.ID, "MainArea_FromMonth").click()
    self.driver.find_element(By.ID, "MainArea_FromYear").click()
    self.driver.find_element(By.ID, "MainArea_FromYear").click()
    self.driver.find_element(By.ID, "MainArea_ToMonth").click()
    dropdown = self.driver.find_element(By.ID, "MainArea_ToMonth")
    dropdown.find_element(By.XPATH, "//option[. = '01']").click()
    self.driver.find_element(By.ID, "MainArea_ToMonth").click()
    self.driver.find_element(By.ID, "MainArea_ToYear").click()
    self.driver.find_element(By.ID, "MainArea_ToYear").click()
    
    dropdown = self.driver.find_element(By.ID, "MainArea_FrTo_Label")
    dropdown.find_element(By.XPATH, "//option[. = '- All Labels -']").click()
    dropdown = self.driver.find_element(By.ID, "MainArea_FrTo_Label")
    dropdown.find_element(By.XPATH, "//option[. = '- All Naxos Labels -']").click()
    self.driver.find_element(By.CSS_SELECTOR, "#MainArea_FrTo_DSP > option:nth-child(1)").click()
    element = self.driver.find_element(By.ID, "MainArea_FrTo_Country")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.ID, "MainArea_FrTo_Country")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.ID, "MainArea_FrTo_Country")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    dropdown = self.driver.find_element(By.ID, "MainArea_FrTo_Country")
    dropdown.find_element(By.XPATH, "//option[. = '- All Countries -']").click()
    dropdown = self.driver.find_element(By.ID, "MainArea_FrTo_Country")
    dropdown.find_element(By.XPATH, "//option[. = 'UNITED STATES OF AMERICA']").click()
    dropdown = self.driver.find_element(By.ID, "MainArea_FrTo_DeliveryType")
    dropdown.find_element(By.XPATH, "//option[. = '- All Delivery Type -']").click()
    dropdown = self.driver.find_element(By.ID, "MainArea_FrTo_DeliveryType")
    dropdown.find_element(By.XPATH, "//option[. = 'DOWNLOAD']").click()
    self.driver.find_element(By.ID, "MainArea_FrTo_ReportingOffice").click()
    dropdown = self.driver.find_element(By.ID, "MainArea_FrTo_ReportingOffice")
    dropdown.find_element(By.XPATH, "//option[. = 'Naxos of America Inc.']").click()
    self.driver.find_element(By.ID, "MainArea_FrTo_ReportingOffice").click()
    self.driver.find_element(By.ID, "MainArea_FrTo_Item").click()
    self.driver.find_element(By.ID, "MainArea_FrTo_Item").send_keys("8.579025")
    self.driver.find_element(By.ID, "MainArea_ReportType").click()
    self.driver.find_element(By.ID, "MainArea_ReportType").click()
    self.driver.find_element(By.ID, "MainArea_FileFormat").click()
    self.driver.find_element(By.ID, "MainArea_FileFormat").click()
    self.driver.find_element(By.ID, "MainArea_CompressExport").click()
    self.driver.find_element(By.ID, "MainArea_CompressExport").click()
    self.driver.find_element(By.ID, "MainArea_ExportButton").click()
  
